version: '3.3'
services:
  api:
    build: .
    ports:
        - "8000:8000"
    volumes:
        - ../:/usr/src/app
    command: bash -c "./app.sh api install_module && npm start"
  api-test:
    build: .
    volumes:
        - ../:/usr/src/app
    command: bash -c "./app.sh api install_module && npm test"
